// src/app/(routes)/edges.js
export const initialEdges = [
  {
    id: 'e1-2',
    source: '1',
    target: '2',
    animated: true,
    type: 'smoothstep',
    style: { stroke: '#ff9800', strokeWidth: 2 },
  },
  {
    id: 'e1-3',
    source: '1',
    target: '3',
    animated: true,
    type: 'smoothstep',
    style: { stroke: '#388e3c', strokeWidth: 2 },
  },
  {
    id: 'e1-4',
    source: '1',
    target: '4',
    animated: true,
    type: 'smoothstep',
    style: { stroke: '#f44336', strokeWidth: 2 },
  },
  {
    id: 'e2-5',
    source: '2',
    target: '5',
    type: 'smoothstep',
    style: { stroke: '#ff9800', strokeWidth: 1.5 },
  },
  {
    id: 'e2-6',
    source: '2',
    target: '6',
    type: 'smoothstep',
    style: { stroke: '#ff9800', strokeWidth: 1.5 },
  },
  {
    id: 'e3-7',
    source: '3',
    target: '7',
    type: 'smoothstep',
    style: { stroke: '#388e3c', strokeWidth: 1.5 },
  },
  {
    id: 'e3-8',
    source: '3',
    target: '8',
    type: 'smoothstep',
    style: { stroke: '#388e3c', strokeWidth: 1.5 },
  },
  {
    id: 'e4-9',
    source: '4',
    target: '9',
    type: 'smoothstep',
    style: { stroke: '#f44336', strokeWidth: 1.5 },
  },
  {
    id: 'e4-10',
    source: '4',
    target: '10',
    type: 'smoothstep',
    style: { stroke: '#f44336', strokeWidth: 1.5 },
  },
];
