export const projectsArr = [
    {
        id: '1',
        name: 'Project 1',
        numTeammates: 4,
        skillLevels: ['Beginner', 'Intermediate'],
        hackathonLength: 2,
        tracks: ['education','environment'],
        sponsorChallenges: ['challenge1','challenge2'],
        preferredTools: ['tool1','tool2'],
        specialRequirements: 'Description 1',
        lastUpdated: '2022-10-10',
    },
    {
        id: '2',
        name: 'Project 2',
        numTeammates: 4,
        skillLevels: ['Beginner', 'Intermediate'],
        hackathonLength: 2,
        tracks: ['education','environment'],
        sponsorChallenges: ['challenge1','challenge2'],
        preferredTools: ['tool1','tool2'],
        specialRequirements: 'Description 2',
        lastUpdated: '2022-10-10',
    },
    {
        id: '3',
        name: 'Project 3',
        numTeammates: 4,
        skillLevels: ['Beginner', 'Intermediate'],
        hackathonLength: 2,
        tracks: ['education','environment'],
        sponsorChallenges: ['challenge1','challenge2'],
        preferredTools: ['tool1','tool2'],
        specialRequirements: 'Description 3',
        lastUpdated: '2022-10-10',
    },
    {
        id: '4',
        name: 'Project 4',
        numTeammates: 4,
        skillLevels: ['Beginner', 'Intermediate'],
        hackathonLength: 2,
        tracks: ['education','environment'],
        sponsorChallenges: ['challenge1','challenge2'],
        preferredTools: ['tool1','tool2'],
        specialRequirements: 'Description 4',
        lastUpdated: '2022-10-10',
    },
]